// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADiI8Hpj8-m1ZQQAND5-9eHr2nCcnUdyA',
    appId: '1:1010001325709:web:3dabe8582152632ef93cc4',
    messagingSenderId: '1010001325709',
    projectId: 'fir-demo-ac999',
    authDomain: 'fir-demo-ac999.firebaseapp.com',
    storageBucket: 'fir-demo-ac999.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOPZkHOM4OqNGBuuD_dBpT-ZJN78BKc8',
    appId: '1:1010001325709:android:e7799e9038aeb02ef93cc4',
    messagingSenderId: '1010001325709',
    projectId: 'fir-demo-ac999',
    storageBucket: 'fir-demo-ac999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_olRlcqgab_ihFS-5hI6_C15G3tFA548',
    appId: '1:1010001325709:ios:8a28e7e13318d9cff93cc4',
    messagingSenderId: '1010001325709',
    projectId: 'fir-demo-ac999',
    storageBucket: 'fir-demo-ac999.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_olRlcqgab_ihFS-5hI6_C15G3tFA548',
    appId: '1:1010001325709:ios:7ff65643c532bdc6f93cc4',
    messagingSenderId: '1010001325709',
    projectId: 'fir-demo-ac999',
    storageBucket: 'fir-demo-ac999.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
